apiVersion: skaffold/v2beta6
kind: Config
deploy:
  helm:
    releases:
      - name: ingress
        chartPath: .\dev_depl\helm\
        valuesFiles:
          - .\dev_depl\helm\ingress-values.yaml
      - name: redis-bullmq
        chartPath: .\dev_depl\helm\
        valuesFiles:
          - .\dev_depl\helm\redis-values.yaml
        setValues:
          volumes.pvc.name: bullmq
          volumes.pvc.existing_claim:
      - name: annot
        chartPath: .\dev_depl\helm\
        valuesFiles:
          - .\dev_depl\helm\values.yaml
        artifactOverrides:
          image: cubrenig/pgwasannot

build:
  local:
    push: false
    concurrency: 5
  artifacts:
    - image: cubrenig/pgwasannot
      context: app
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "**/*.R"
            dest: .
          - src: "**/*.sh"
            dest: .
