FROM node:16

ENV CI=true

WORKDIR /app

COPY package.json ./

#COPY yarn.lock ./

RUN yarn add @nestjs/cli --verbose

RUN yarn install

COPY ./ ./

RUN chmod 775 pipeline_scripts/annotation_script-1.sh
RUN chmod 775 pipeline_scripts/deleteriousness_script.sh
RUN chmod 775 pipeline_scripts/disgenet_script.R
RUN chmod 775 pipeline_scripts/filter_exonic.R

#install R and packages
RUN apt update

RUN apt-get install -y r-base

RUN apt-get install -y -qq r-cran-ggplot2

RUN apt-get install dos2unix
RUN dos2unix pipeline_scripts/annotation_script-1.sh
RUN dos2unix pipeline_scripts/disgenet_script.R

#RUN R -e "install.packages(c('ggplot2'),dependencies=TRUE,repos='http://cran.rstudio.com/')"

#RUN yarn run build
CMD [ "yarn", "run", "start:dev" ]
